Sample 3ds new flow
Midtrans/midtrans-php pull request #58
Opened 2021-09-13 05:22 UTC by omarxp

move authentication (3DS) param to backend

2021-09-13 10:16 UTC, rizdaprasetya requested changes
👍 nice. but since the example code is old and not updated for a long time, I think we can improve this. Please follow the commented suggestion. Thanks @omarxp

2021-09-13 10:16 UTC, rizdaprasetya commented on examples/notification-handler.php
> +}
This block is not part of the example. Can be confusing to read this part of code. Can you make it a function that is defined in a bottom?

e.g. at the bottom of  this file:
```
// non-relevant function only used for demo/example purpose
function printExampleWarningMessage(){
...
}
```
Then call it on line 11.

Also within that function check if method is not POST, then print warning: 
Notification-handler are not meant to be opened via browser / GET HTTP method. It is used to handle Midtrans HTTP POST notification / webhook. <put link to docs about notif handling>

2021-09-13 10:16 UTC, rizdaprasetya commented on examples/snap-redirect/checkout-process.php
> +}
refactor as function `printExampleWarningMessage()`. Also applies to other file that have this codeblock

2021-09-13 10:16 UTC, rizdaprasetya commented on examples/core-api/checkout.php
> +            var callback = {
better let's rename this var to `getCardTokenCallback` for more descriptive code

2021-09-13 10:16 UTC, rizdaprasetya commented on examples/core-api/checkout.php
> +    echo "<h4>Please set your server key from sandbox</h4>";
message should be `client key`, not `server key`. Also refactor as `printExampleWarningMessage` function

2021-09-14 09:22 UTC, omarxp commented
@rizdaprasetya add a new commit for PR feedback

2021-09-14 11:10 UTC, rizdaprasetya approved these changes
Nice, looks good now 👍 please go ahead merge. Thanks @omarxp !

2021-09-15 03:07 UTC, merged